# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 180)
        MainWindow.setMinimumSize(QtCore.QSize(800, 180))
        MainWindow.setMaximumSize(QtCore.QSize(800, 180))
        font = QtGui.QFont()
        font.setFamily("DejaVu Math TeX Gyre")
        MainWindow.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("favicon.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tagsQueryLabel = QtWidgets.QLabel(self.centralwidget)
        self.tagsQueryLabel.setGeometry(QtCore.QRect(10, 30, 101, 21))
        font = QtGui.QFont()
        font.setFamily("DejaVu Math TeX Gyre")
        font.setPointSize(9)
        self.tagsQueryLabel.setFont(font)
        self.tagsQueryLabel.setObjectName("tagsQueryLabel")
        self.tagsQueryLineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.tagsQueryLineEdit.setGeometry(QtCore.QRect(110, 30, 201, 22))
        font = QtGui.QFont()
        font.setFamily("DejaVu Math TeX Gyre")
        font.setPointSize(8)
        self.tagsQueryLineEdit.setFont(font)
        self.tagsQueryLineEdit.setText("")
        self.tagsQueryLineEdit.setObjectName("tagsQueryLineEdit")
        self.pageCountLabel = QtWidgets.QLabel(self.centralwidget)
        self.pageCountLabel.setGeometry(QtCore.QRect(10, 70, 101, 21))
        font = QtGui.QFont()
        font.setFamily("DejaVu Math TeX Gyre")
        font.setPointSize(9)
        self.pageCountLabel.setFont(font)
        self.pageCountLabel.setObjectName("pageCountLabel")
        self.pageCountSpinBox = QtWidgets.QSpinBox(self.centralwidget)
        self.pageCountSpinBox.setGeometry(QtCore.QRect(110, 70, 71, 22))
        font = QtGui.QFont()
        font.setFamily("DejaVu Math TeX Gyre")
        self.pageCountSpinBox.setFont(font)
        self.pageCountSpinBox.setMinimum(1)
        self.pageCountSpinBox.setMaximum(10000)
        self.pageCountSpinBox.setObjectName("pageCountSpinBox")
        self.savePathLabel = QtWidgets.QLabel(self.centralwidget)
        self.savePathLabel.setGeometry(QtCore.QRect(10, 110, 101, 21))
        font = QtGui.QFont()
        font.setFamily("DejaVu Math TeX Gyre")
        font.setPointSize(9)
        self.savePathLabel.setFont(font)
        self.savePathLabel.setObjectName("savePathLabel")
        self.savePathLineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.savePathLineEdit.setGeometry(QtCore.QRect(110, 110, 131, 22))
        self.savePathLineEdit.setText("")
        self.savePathLineEdit.setReadOnly(True)
        self.savePathLineEdit.setObjectName("savePathLineEdit")
        self.explicitContentCheckBox = QtWidgets.QCheckBox(self.centralwidget)
        self.explicitContentCheckBox.setGeometry(QtCore.QRect(230, 150, 16, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.explicitContentCheckBox.setFont(font)
        self.explicitContentCheckBox.setText("")
        self.explicitContentCheckBox.setTristate(False)
        self.explicitContentCheckBox.setObjectName("explicitContentCheckBox")
        self.explicitContentLabel = QtWidgets.QLabel(self.centralwidget)
        self.explicitContentLabel.setGeometry(QtCore.QRect(10, 150, 211, 21))
        font = QtGui.QFont()
        font.setFamily("DejaVu Math TeX Gyre")
        font.setPointSize(9)
        self.explicitContentLabel.setFont(font)
        self.explicitContentLabel.setObjectName("explicitContentLabel")
        self.savePathPushButton = QtWidgets.QPushButton(self.centralwidget)
        self.savePathPushButton.setGeometry(QtCore.QRect(240, 110, 71, 21))
        self.savePathPushButton.setObjectName("savePathPushButton")
        self.startPushButton = QtWidgets.QPushButton(self.centralwidget)
        self.startPushButton.setGeometry(QtCore.QRect(460, 30, 181, 41))
        self.startPushButton.setObjectName("startPushButton")
        self.stopPushButton = QtWidgets.QPushButton(self.centralwidget)
        self.stopPushButton.setGeometry(QtCore.QRect(640, 30, 111, 41))
        self.stopPushButton.setObjectName("stopPushButton")
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setGeometry(QtCore.QRect(460, 80, 331, 21))
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.statusLabel = QtWidgets.QLabel(self.centralwidget)
        self.statusLabel.setGeometry(QtCore.QRect(460, 110, 291, 41))
        self.statusLabel.setText("")
        self.statusLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.statusLabel.setObjectName("statusLabel")
        MainWindow.setCentralWidget(self.centralwidget)
        self.actionAuthor = QtWidgets.QAction(MainWindow)
        self.actionAuthor.setObjectName("actionAuthor")

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "yande.re_parser"))
        self.tagsQueryLabel.setText(_translate("MainWindow", "Tags Query:"))
        self.pageCountLabel.setText(_translate("MainWindow", "Page count:"))
        self.savePathLabel.setText(_translate("MainWindow", "Save to:"))
        self.explicitContentLabel.setText(_translate("MainWindow", "Download explicit content:"))
        self.savePathPushButton.setText(_translate("MainWindow", "Choose..."))
        self.startPushButton.setText(_translate("MainWindow", "START"))
        self.stopPushButton.setText(_translate("MainWindow", "STOP"))
        self.actionAuthor.setText(_translate("MainWindow", "Author"))
