# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qtdesign.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 250)
        MainWindow.setMinimumSize(QtCore.QSize(800, 200))
        MainWindow.setMaximumSize(QtCore.QSize(800, 250))
        font = QtGui.QFont()
        font.setFamily("DejaVu Math TeX Gyre")
        MainWindow.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("favicon.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setToolTip("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tagsQueryLabel = QtWidgets.QLabel(self.centralwidget)
        self.tagsQueryLabel.setGeometry(QtCore.QRect(10, 20, 101, 21))
        font = QtGui.QFont()
        font.setFamily("DejaVu Math TeX Gyre")
        font.setPointSize(9)
        self.tagsQueryLabel.setFont(font)
        self.tagsQueryLabel.setStatusTip("")
        self.tagsQueryLabel.setWhatsThis("")
        self.tagsQueryLabel.setObjectName("tagsQueryLabel")
        self.tagsQueryLineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.tagsQueryLineEdit.setGeometry(QtCore.QRect(110, 20, 201, 22))
        font = QtGui.QFont()
        font.setFamily("DejaVu Math TeX Gyre")
        font.setPointSize(8)
        self.tagsQueryLineEdit.setFont(font)
        self.tagsQueryLineEdit.setText("")
        self.tagsQueryLineEdit.setObjectName("tagsQueryLineEdit")
        self.pageCountLabel = QtWidgets.QLabel(self.centralwidget)
        self.pageCountLabel.setGeometry(QtCore.QRect(10, 60, 101, 21))
        font = QtGui.QFont()
        font.setFamily("DejaVu Math TeX Gyre")
        font.setPointSize(9)
        self.pageCountLabel.setFont(font)
        self.pageCountLabel.setObjectName("pageCountLabel")
        self.pageCountSpinBox = QtWidgets.QSpinBox(self.centralwidget)
        self.pageCountSpinBox.setGeometry(QtCore.QRect(110, 60, 71, 22))
        font = QtGui.QFont()
        font.setFamily("DejaVu Math TeX Gyre")
        self.pageCountSpinBox.setFont(font)
        self.pageCountSpinBox.setMinimum(1)
        self.pageCountSpinBox.setMaximum(10000)
        self.pageCountSpinBox.setObjectName("pageCountSpinBox")
        self.savePathLabel = QtWidgets.QLabel(self.centralwidget)
        self.savePathLabel.setGeometry(QtCore.QRect(10, 100, 101, 21))
        font = QtGui.QFont()
        font.setFamily("DejaVu Math TeX Gyre")
        font.setPointSize(9)
        self.savePathLabel.setFont(font)
        self.savePathLabel.setObjectName("savePathLabel")
        self.savePathLineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.savePathLineEdit.setGeometry(QtCore.QRect(110, 100, 181, 22))
        self.savePathLineEdit.setText("")
        self.savePathLineEdit.setReadOnly(True)
        self.savePathLineEdit.setObjectName("savePathLineEdit")
        self.explicitContentCheckBox = QtWidgets.QCheckBox(self.centralwidget)
        self.explicitContentCheckBox.setGeometry(QtCore.QRect(230, 140, 16, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.explicitContentCheckBox.setFont(font)
        self.explicitContentCheckBox.setText("")
        self.explicitContentCheckBox.setTristate(False)
        self.explicitContentCheckBox.setObjectName("explicitContentCheckBox")
        self.explicitContentLabel = QtWidgets.QLabel(self.centralwidget)
        self.explicitContentLabel.setGeometry(QtCore.QRect(10, 140, 211, 21))
        font = QtGui.QFont()
        font.setFamily("DejaVu Math TeX Gyre")
        font.setPointSize(9)
        self.explicitContentLabel.setFont(font)
        self.explicitContentLabel.setObjectName("explicitContentLabel")
        self.savePathPushButton = QtWidgets.QPushButton(self.centralwidget)
        self.savePathPushButton.setGeometry(QtCore.QRect(290, 100, 21, 21))
        self.savePathPushButton.setObjectName("savePathPushButton")
        self.startPushButton = QtWidgets.QPushButton(self.centralwidget)
        self.startPushButton.setGeometry(QtCore.QRect(460, 20, 181, 41))
        self.startPushButton.setObjectName("startPushButton")
        self.stopPushButton = QtWidgets.QPushButton(self.centralwidget)
        self.stopPushButton.setGeometry(QtCore.QRect(640, 20, 111, 41))
        self.stopPushButton.setObjectName("stopPushButton")
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setGeometry(QtCore.QRect(460, 70, 331, 21))
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.statusLabel = QtWidgets.QLabel(self.centralwidget)
        self.statusLabel.setGeometry(QtCore.QRect(460, 100, 291, 41))
        self.statusLabel.setText("")
        self.statusLabel.setTextFormat(QtCore.Qt.AutoText)
        self.statusLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.statusLabel.setObjectName("statusLabel")
        self.numberOfProcessesLabel = QtWidgets.QLabel(self.centralwidget)
        self.numberOfProcessesLabel.setGeometry(QtCore.QRect(10, 190, 181, 21))
        font = QtGui.QFont()
        font.setFamily("DejaVu Math TeX Gyre")
        font.setPointSize(9)
        self.numberOfProcessesLabel.setFont(font)
        self.numberOfProcessesLabel.setObjectName("numberOfProcessesLabel")
        self.numberOfProcessesSpinBox = QtWidgets.QSpinBox(self.centralwidget)
        self.numberOfProcessesSpinBox.setGeometry(QtCore.QRect(190, 190, 51, 22))
        self.numberOfProcessesSpinBox.setMinimum(2)
        self.numberOfProcessesSpinBox.setMaximum(100)
        self.numberOfProcessesSpinBox.setProperty("value", 12)
        self.numberOfProcessesSpinBox.setObjectName("numberOfProcessesSpinBox")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(0, 165, 800, 20))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.numberOfProcessSetPushButton = QtWidgets.QPushButton(self.centralwidget)
        self.numberOfProcessSetPushButton.setGeometry(QtCore.QRect(250, 190, 51, 21))
        self.numberOfProcessSetPushButton.setObjectName("numberOfProcessSetPushButton")
        self.imageFormatLabel = QtWidgets.QLabel(self.centralwidget)
        self.imageFormatLabel.setGeometry(QtCore.QRect(460, 190, 121, 21))
        font = QtGui.QFont()
        font.setFamily("DejaVu Math TeX Gyre")
        font.setPointSize(9)
        self.imageFormatLabel.setFont(font)
        self.imageFormatLabel.setObjectName("imageFormatLabel")
        self.pngRadioButton = QtWidgets.QRadioButton(self.centralwidget)
        self.pngRadioButton.setGeometry(QtCore.QRect(580, 190, 61, 20))
        self.pngRadioButton.setObjectName("pngRadioButton")
        self.jpegRadioButton = QtWidgets.QRadioButton(self.centralwidget)
        self.jpegRadioButton.setGeometry(QtCore.QRect(640, 190, 61, 20))
        self.jpegRadioButton.setChecked(True)
        self.jpegRadioButton.setObjectName("jpegRadioButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menuBar.setObjectName("menuBar")
        self.menuAbout = QtWidgets.QMenu(self.menuBar)
        self.menuAbout.setObjectName("menuAbout")
        self.menuSettings = QtWidgets.QMenu(self.menuBar)
        self.menuSettings.setObjectName("menuSettings")
        MainWindow.setMenuBar(self.menuBar)
        self.actionAuthor = QtWidgets.QAction(MainWindow)
        self.actionAuthor.setObjectName("actionAuthor")
        self.actionAuthor_2 = QtWidgets.QAction(MainWindow)
        self.actionAuthor_2.setObjectName("actionAuthor_2")
        self.actionMultiprocessing = QtWidgets.QAction(MainWindow)
        self.actionMultiprocessing.setObjectName("actionMultiprocessing")
        self.menuAbout.addAction(self.actionAuthor_2)
        self.menuSettings.addAction(self.actionMultiprocessing)
        self.menuBar.addAction(self.menuAbout.menuAction())
        self.menuBar.addAction(self.menuSettings.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "yande.re_parser"))
        self.tagsQueryLabel.setToolTip(_translate("MainWindow", "Tags for search; ex.: azur_lane wallpaper"))
        self.tagsQueryLabel.setText(_translate("MainWindow", "Tags Query:"))
        self.pageCountLabel.setToolTip(_translate("MainWindow", "Number of pages for parsing; ex.: 5;  1 page ≈ 40 images"))
        self.pageCountLabel.setText(_translate("MainWindow", "Page count:"))
        self.savePathLabel.setToolTip(_translate("MainWindow", "Choosing a save path; ex.: D:\\temp"))
        self.savePathLabel.setText(_translate("MainWindow", "Save to:"))
        self.explicitContentLabel.setToolTip(_translate("MainWindow", "Explicit content confirm; may not work"))
        self.explicitContentLabel.setText(_translate("MainWindow", "Download explicit content:"))
        self.savePathPushButton.setText(_translate("MainWindow", "..."))
        self.startPushButton.setToolTip(_translate("MainWindow", "Start parsing"))
        self.startPushButton.setText(_translate("MainWindow", "START"))
        self.stopPushButton.setToolTip(_translate("MainWindow", "Stop parsing"))
        self.stopPushButton.setText(_translate("MainWindow", "STOP"))
        self.numberOfProcessesLabel.setToolTip(_translate("MainWindow", "More processes - faster, but don\'t go too far"))
        self.numberOfProcessesLabel.setText(_translate("MainWindow", "Number of processes:"))
        self.numberOfProcessSetPushButton.setToolTip(_translate("MainWindow", "Fix spinbox value"))
        self.numberOfProcessSetPushButton.setText(_translate("MainWindow", "Set"))
        self.imageFormatLabel.setToolTip(_translate("MainWindow", "Choose image format for all downloads"))
        self.imageFormatLabel.setText(_translate("MainWindow", "Image format:"))
        self.pngRadioButton.setToolTip(_translate("MainWindow", "more quality, less speed"))
        self.pngRadioButton.setText(_translate("MainWindow", "PNG"))
        self.jpegRadioButton.setToolTip(_translate("MainWindow", "less quality, more speed"))
        self.jpegRadioButton.setText(_translate("MainWindow", "JPEG"))
        self.menuAbout.setTitle(_translate("MainWindow", "About"))
        self.menuSettings.setTitle(_translate("MainWindow", "Other"))
        self.actionAuthor.setText(_translate("MainWindow", "Author"))
        self.actionAuthor_2.setText(_translate("MainWindow", "Author"))
        self.actionMultiprocessing.setText(_translate("MainWindow", "Show MP settings"))
